spring:
  profiles:
    active: local
  application:
    name: map
############# Data Source ######
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:172.31.46.83}:3306/map?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: "map_user"
    password: "map_password"
############# Batch ############
  batch:
    job:
      name: "retrip-map"
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#logging:
#  level:
    # 1. Spring Data ES의 최상위 로그
#    org.springframework.data.elasticsearch.client.WIRE: TRACE
    # 2. Elasticsearch 자바 클라이언트의 저수준 Tracer (핵심!)
#    org.elasticsearch.client.tracer: TRACE
    # 3. Apache HttpClient를 사용 중이라면 필수 (전송 데이터 확인)
#    org.apache.http.wire: DEBUG
jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlfO/CoX9EzhskpAKX9ADH0wfEQZP4rAq
    ptqq80W2YaOHAnXu+oU1UrP0b9ccKKSzMCVDwdmXrecZB0dFLPnoazMEbVOf6MSwrhGfxupPRmmJ
    sIYgmQwo8/vnjaq/GYFfnHyCy6yKL41G+GZVqgeKdhr+w1jUw4L9Fs0l2J/AYqwTxZOnzxrU5erP
    GSE5Dd3AwWt/brxuwA7sRfVS3mbbsYyYExjUrEbst8VtF3Pis35T8YfSDKMOUgiDnp30EAdGU1Up
    u59J3+ToLRrIqIszRZqmasrWTL2/ihPO76PSTIMAsJMScjAwjUXA47YOOy6Vkzy8r3bPTYHp5C1N
    KucWwwIDAQAB
    -----END PUBLIC KEY-----
#logging:
#  level:
    #tracer: TRACE
    #org.springframework.data.elasticsearch.client.WIRE: TRACE
    #org.elasticsearch.client.RestClient: TRACE
    #org.springframework.data.elasticsearch.core: DEBUG