spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:map;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

elasticsearch:
  host: 43.203.150.52
  port: 9200
  scheme: http
