spring:
  application:
    name: map
############# Data Source ######
  datasource:
    url: jdbc:mysql://localhost:3306/map?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
############# Batch ############
  batch:
    job:
      name: "retrip-map"
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    # 쿼리 실행 결과 및 기본 정보를 확인
    org.springframework.data.elasticsearch.core: DEBUG
    # 실제 HTTP 통신(Request/Response Body)을 상세히 확인 (가장 권장)
    org.springframework.data.elasticsearch.client.WIRE: TRACE
